version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # or any valid runtime
    commands:
      - echo Installing Terraform...
      - curl -fsSL https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform -version
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform plan -out=tfplan
  post_build:
    commands:
      - terraform apply -auto-approve tfplan
