version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # optional, just to satisfy runtime requirement
    commands:
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Planning Terraform changes..."
      - terraform plan -out=tfplan -lock=false
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve -lock=false tfplan

